# Generated by Django 5.0.2 on 2024-12-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight',
            new_name='flight_no',
        ),
    ]
